version: "3.8"

services:
  mc1:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      SERVER_NAME: "FrenchGap MC1"
      MOTD: "Serveur MC1 FrenchGap"
      DIFFICULTY: "normal"
      OPS_FILE: "operators.json"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-data:/data
      - ./extras/whitelist.json:/data/whitelist.json
      - ./extras/operators.json:/data/operators.json
    stdin_open: true
    tty: true
    restart: unless-stopped
  networks:
    - mc1

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - type: bind
        source: ./.docker/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - mc
    restart: unless-stopped
    networks:
      - mc1

networks:
  mc1:
    driver: "bridge"
    external: true