version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      SERVER_NAME: "FrenchGap MC1"
      MOTD: "Serveur MC1 FrenchGap"
      DIFFICULTY: "normal"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./extras/whitelist.json:/data/whitelist.json
    stdin_open: true
    tty: true
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - type: bind
        source: ./.docker/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - mc
    restart: unless-stopped

volumes:
  data: {}